from _i18n import LANGUAGE

TRANSLATIONS = {'ja': {'q_age': '年齢を半角数字で入力してください。',
        'q_gender': '性別を選択してください。',
        'q_gender_opts': [[0, '男性'], [1, '女性']],
        'q_lan_jp': 'あなたの母語は日本語ですか？',
        'q_lan_jp_opts': [[1, 'はい'], [0, 'いいえ']],
        'q_affiliate': 'あなたの所属を選択してください',
        'q_kd_affiliate_opts': [[1, '法学部'],
                                [2, '文学部'],
                                [3, '経済学部'],
                                [4, '商学部'],
                                [5, '社会学部'],
                                [6, '政策創作学部'],
                                [7, '外国語学部'],
                                [8, '人間健康学部'],
                                [9, '総合情報学部'],
                                [10, '社会安全学部'],
                                [11, 'システム理工学部'],
                                [12, '環境都市工学部'],
                                [13, '化学生命工学部'],
                                [14, '法学研究科'],
                                [15, '文学研究科'],
                                [16, '経済学研究科'],
                                [17, '商学研究科'],
                                [18, '社会学研究科'],
                                [19, '総合情報学研究科'],
                                [20, '理工学研究科'],
                                [21, '外国語教育学研究科'],
                                [22, '心理学研究科'],
                                [23, '社会安全研究科'],
                                [24, '東アジア文学研究科'],
                                [25, 'ガバナンス研究科'],
                                [26, '人間健康研究科'],
                                [27, '法務研究科'],
                                [28, '会計研究科']],
        'q_chatGPT': 'ChatGPTのことを聞いたことがありますか？',
        'q_chatGPT_opts': [[1, 'はい'], [0, 'いいえ']],
        'q_chatGPT_plus': 'ChatGPT Plus (ChatGPTの有料版)\u3000を使ったことがありますか？',
        'q_chatGPT_plus_opts': [[1, 'はい'], [0, 'いいえ']],
        'title': 'アンケート',
        'submit': '回答を送信して最終結果を見る',
        'q_chatGPT_times': '週平均で何日間ChatGPTを使用していますか？（0から7までの整数を入力してください）',
        'experience_title': '課題の経験とAIについて',
        'next': '次へ',
        'q_competition_pressure': 'メインタスクの第2段階（トーナメント方式）で、どの程度プレッシャーを感じましたか？',
        'q_ai_performance_impact': '本日のメインタスクで、生成AIアシスタントを使用する場合、使用しない場合と比べて、あなたの成績にどのような影響があると思いますか？',
        'q_ai_expected_accuracy': '生成AIアシスタントが本日のメインタスクの問題に回答するとしたら、その平均正答率は何％になると思いますか？（0〜100％の数値を入力してください）',
        'q_investment_experience': '株式または投資信託への投資経験はありますか？',
        'q_finance_course': '金融または経済学に関する授業を履修したことはありますか？',
        'pressure_choices': [[1, '1 — まったく感じなかった'],
                             [2, '2 — ほとんど感じなかった'],
                             [3, '3 — あまり感じなかった'],
                             [4, '4 — 中程度に感じた'],
                             [5, '5 — やや強く感じた'],
                             [6, '6 — 強く感じた'],
                             [7, '7 — 非常に強く感じた']],
        'impact_choices': [[1, '1 — 成績が大幅に下がる'],
                           [2, '2 — 成績が下がる'],
                           [3, '3 — 成績が少し下がる'],
                           [4, '4 — 成績は変わらない'],
                           [5, '5 — 成績が少し上がる'],
                           [6, '6 — 成績が上がる'],
                           [7, '7 — 成績が大幅に上がる']]},
 'en': {'title': 'Questionnaire',
        'submit': 'Submit answers and view final results',
        'q_age': 'Please enter your age.',
        'q_gender': 'Please select your gender.',
        'q_lan_jp': 'Is Japanese your native language?',
        'q_affiliate': 'Please select your faculty or graduate school.',
        'q_chatGPT': 'Have you heard of ChatGPT?',
        'q_chatGPT_times': 'On average, how many days per week do you use ChatGPT? (Enter an integer from 0 '
                           'to 7.)',
        'q_chatGPT_plus': 'Have you ever used ChatGPT Plus (the paid version of ChatGPT)?',
        'q_gender_opts': [[0, 'Male'], [1, 'Female']],
        'q_kd_affiliate_opts': [[1, 'Faculty of Law'],
                                [2, 'Faculty of Letters'],
                                [3, 'Faculty of Economics'],
                                [4, 'Faculty of Business and Commerce'],
                                [5, 'Faculty of Sociology'],
                                [6, 'Faculty of Policy Studies'],
                                [7, 'Faculty of Foreign Language Studies'],
                                [8, 'Faculty of Health and Well-being'],
                                [9, 'Faculty of Informatics'],
                                [10, 'Faculty of Societal Safety Sciences'],
                                [11, 'Faculty of Engineering Science'],
                                [12, 'Faculty of Environmental and Urban Engineering'],
                                [13, 'Faculty of Chemistry, Materials and Bioengineering'],
                                [14, 'Graduate School of Law'],
                                [15, 'Graduate School of Letters'],
                                [16, 'Graduate School of Economics'],
                                [17, 'Graduate School of Business and Commerce'],
                                [18, 'Graduate School of Sociology'],
                                [19, 'Graduate School of Informatics'],
                                [20, 'Graduate School of Science and Engineering'],
                                [21, 'Graduate School of Foreign Language Education and Research'],
                                [22, 'Graduate School of Psychology'],
                                [23, 'Graduate School of Societal Safety Sciences'],
                                [24, 'Graduate School of East Asian Cultures'],
                                [25, 'Graduate School of Governance'],
                                [26, 'Graduate School of Health and Well-being'],
                                [27, 'Law School'],
                                [28, 'School of Accountancy']],
        'q_lan_jp_opts': [[1, 'Yes'], [0, 'No']],
        'q_chatGPT_opts': [[1, 'Yes'], [0, 'No']],
        'q_chatGPT_plus_opts': [[1, 'Yes'], [0, 'No']],
        'experience_title': 'Task experience and AI',
        'next': 'Next',
        'q_competition_pressure': 'How much pressure did you feel during the second stage of the main task '
                                  '(tournament payment)?',
        'q_ai_performance_impact': 'For today’s main task, how do you think using a generative AI assistant '
                                   'would affect your performance compared with not using one?',
        'q_ai_expected_accuracy': 'If a generative AI assistant answered questions from today’s main task, '
                                  'what do you predict its average percentage of correct answers would be? '
                                  '(Enter a number from 0 to 100%.)',
        'q_investment_experience': 'Have you ever invested in stocks or investment funds?',
        'q_finance_course': 'Have you taken any finance or economics courses?',
        'pressure_choices': [[1, '1 — None at all'],
                             [2, '2 — Very little'],
                             [3, '3 — A little'],
                             [4, '4 — Moderate'],
                             [5, '5 — Quite a lot'],
                             [6, '6 — A lot'],
                             [7, '7 — A great deal']],
        'impact_choices': [[1, '1 — Greatly decrease my performance'],
                           [2, '2 — Decrease my performance'],
                           [3, '3 — Slightly decrease my performance'],
                           [4, '4 — No effect on my performance'],
                           [5, '5 — Slightly increase my performance'],
                           [6, '6 — Increase my performance'],
                           [7, '7 — Greatly increase my performance']]},
 'zh-hans': {'title': '问卷',
             'submit': '提交回答并查看最终结果',
             'q_age': '请输入你的年龄。',
             'q_gender': '请选择你的性别。',
             'q_lan_jp': '日语是你的母语吗？',
             'q_affiliate': '请选择你所属的学部或研究科。',
             'q_chatGPT': '你是否听说过 ChatGPT？',
             'q_chatGPT_times': '你平均每周有几天使用 ChatGPT？（请输入0至7之间的整数）',
             'q_chatGPT_plus': '你是否使用过 ChatGPT Plus（ChatGPT的付费版）？',
             'q_gender_opts': [[0, '男'], [1, '女']],
             'q_kd_affiliate_opts': [[1, '法学部'],
                                     [2, '文学部'],
                                     [3, '经济学部'],
                                     [4, '商学部'],
                                     [5, '社会学部'],
                                     [6, '政策创造学部'],
                                     [7, '外国语学部'],
                                     [8, '人类健康学部'],
                                     [9, '综合信息学部'],
                                     [10, '社会安全学部'],
                                     [11, '系统理工学部'],
                                     [12, '环境都市工学部'],
                                     [13, '化学生命工学部'],
                                     [14, '法学研究科'],
                                     [15, '文学研究科'],
                                     [16, '经济学研究科'],
                                     [17, '商学研究科'],
                                     [18, '社会学研究科'],
                                     [19, '综合信息学研究科'],
                                     [20, '理工学研究科'],
                                     [21, '外语教育学研究科'],
                                     [22, '心理学研究科'],
                                     [23, '社会安全研究科'],
                                     [24, '东亚文化研究科'],
                                     [25, '治理研究科'],
                                     [26, '人类健康研究科'],
                                     [27, '法务研究科'],
                                     [28, '会计研究科']],
             'q_lan_jp_opts': [[1, '是'], [0, '否']],
             'q_chatGPT_opts': [[1, '是'], [0, '否']],
             'q_chatGPT_plus_opts': [[1, '是'], [0, '否']],
             'experience_title': '任务体验与AI',
             'next': '下一步',
             'q_competition_pressure': '在主任务第二轮的竞赛报酬阶段，你感到多大压力？',
             'q_ai_performance_impact': '对于今天的主任务，相比不使用生成式AI助手，你认为使用生成式AI助手会对自己的表现产生什么影响？',
             'q_ai_expected_accuracy': '如果让生成式AI助手回答今天主任务中的题目，你预测它的平均正确率是多少？（请输入0～100%的数值）',
             'q_investment_experience': '你是否有股票或基金投资经验？',
             'q_finance_course': '你是否学过金融或经济学课程？',
             'pressure_choices': [[1, '1 — 完全没有'],
                                  [2, '2 — 非常小'],
                                  [3, '3 — 较小'],
                                  [4, '4 — 中等'],
                                  [5, '5 — 较大'],
                                  [6, '6 — 很大'],
                                  [7, '7 — 非常大']],
             'impact_choices': [[1, '1 — 大大降低自己的表现'],
                                [2, '2 — 降低自己的表现'],
                                [3, '3 — 略微降低自己的表现'],
                                [4, '4 — 没有影响'],
                                [5, '5 — 略微提高自己的表现'],
                                [6, '6 — 提高自己的表现'],
                                [7, '7 — 大大提高自己的表现']]}}

TEXT = TRANSLATIONS[LANGUAGE]


class Lexicon:
    pass


for key, value in TEXT.items():
    setattr(Lexicon, key, value)
