from _i18n import LANGUAGE

TRANSLATIONS = {'ja': {'title': 'クイズ',
        'instructions_title': 'クイズの説明',
        'answer': '回答',
        'next': '次へ',
        'timer': '残り時間：',
        'complete': 'クイズ終了',
        'complete_body': '7つのクイズが終了しました。続いてアンケートにお答えください。報酬はアンケート回答後の最終結果画面で表示されます。',
        'to_questionnaire': 'アンケートに進む',
        'questions': ['マリオがピザ1枚を5分で食べることができ、ジョンがピザ1枚を20分で食べる場合、二人でピザ1枚を食べるのにどれくらいの時間がかかりますか？（分単位の数値を入力してください）',
                      'メアリーはクラスで18番目に高い点数と18番目に低い点数の両方を受け取りました。クラスには何人の生徒がいますか？（数値を入力してください）',
                      '投資家が会社を8000万円で購入し、9000万円で売却し、9500万円で再購入し、最終的に1億1000万円で売却しました。彼の利益は何百万円ですか？（百万円単位の数値を入力してください）',
                      'ウォーレンは2018年に100万円分の株を購入しました。投資してから6ヶ月後の8月11日には、彼が購入した株は40%下落しました。幸いなことに、8月11日から11月11日までの間に、彼が購入した株は60%上昇しました。この時点でウォーレンは：',
                      'バットとボールの値段は合わせて5,500円です。バットはボールより5,000円高いです。ボールの値段はいくらですか？（円単位の数値を入力してください）',
                      '5台の機械が5個の製品を作るのに5分かかります。100台の機械が100個の製品を作るには何分かかりますか？（数値を入力してください）',
                      '池にスイレンが生えています。スイレンが覆う面積は毎日2倍になります。池全体を覆うのに48日かかるとすると、池の半分を覆うのに何日かかりますか？（数値を入力してください）'],
        'choices': [['A', 'A. 2018年以来、お金を稼いでも損もしていない。'],
                    ['B', 'B. 2018年以来、お金を稼いでいる。'],
                    ['C', 'C. 2018年以来、お金を失っている。']],
        'instructions': ['これから、あなたに7つのクイズを回答してもらいます。',
                         'それぞれの問題を正しく解答した場合、1問正解ごとに20円の報酬が発生します。',
                         '各問題には60秒の制限時間が設けられており、60秒以内に回答できなかった場合は不正解とみなされます。',
                         'また、各クイズを回答した後、「次へ」ボタンを押すと次のクイズに進みます。一度回答を決定すると、元のクイズに戻って回答を変更することはできません。',
                         'あなたの報酬は、実験終了後に開示されます。',
                         '以上のルールについて、もし質問がなければ、「次へ」ボタンを押してクイズの回答を開始してください。'],
        'risk_title': '投資の選択',
        'risk_intro': '7つのクイズが終了しました。次に、追加の100円を受け取り、そのうちいくらをリスクのある投資に回すかを決めてください。投資しない金額はそのまま受け取れます。',
        'risk_success': '50%の確率で投資は成功し、投資額の2.5倍（元本を含む）を受け取れます。',
        'risk_failure': '50%の確率で投資は失敗し、投資した金額をすべて失います。',
        'risk_note': '投資額は0〜100円の範囲で、1円単位で入力してください。この選択には正解・不正解や制限時間はありません。結果はコンピューターが無作為に決定し、最終結果画面で報酬とともに表示します。',
        'risk_label': 'いくら投資しますか？（円）',
        'risk_submit': '投資額を決定する',
        'risk_reward': '投資の報酬',
        'risk_invested': '投資額',
        'risk_outcome': '投資結果',
        'risk_won': '成功',
        'risk_lost': '失敗'},
 'en': {'title': 'Quiz',
        'instructions_title': 'Quiz instructions',
        'answer': 'Answer',
        'next': 'Next',
        'timer': 'Time remaining:',
        'complete': 'Quiz complete',
        'complete_body': 'You have completed all seven questions. Please answer the questionnaire next. Your '
                         'earnings will be shown after you submit the questionnaire.',
        'to_questionnaire': 'Continue to questionnaire',
        'questions': ['Mario can eat one pizza in 5 minutes, and John can eat one pizza in 20 minutes. How '
                      'long would it take them to eat one pizza together? (Enter a number in minutes.)',
                      'Mary received both the 18th highest and the 18th lowest score in her class. How many '
                      'students are in the class? (Enter a number.)',
                      'An investor bought a company for 80 million yen, sold it for 90 million yen, bought '
                      'it again for 95 million yen, and finally sold it for 110 million yen. What was his '
                      'profit in millions of yen? (Enter a number in millions of yen.)',
                      'Warren bought 1,000,000 yen worth of stock in 2018. On August 11, six months after he '
                      'invested, the stock had fallen by 40%. Fortunately, between August 11 and November '
                      '11, the stock rose by 60%. At this point, Warren has:',
                      'A bat and a ball cost 5,500 yen in total. The bat costs 5,000 yen more than the ball. '
                      'How much does the ball cost? (Enter a number in yen.)',
                      'If 5 machines take 5 minutes to make 5 products, how many minutes would 100 machines '
                      'take to make 100 products? (Enter a number.)',
                      'There is a patch of water lilies in a pond. The area it covers doubles every day. If '
                      'it takes 48 days to cover the entire pond, how many days does it take to cover half '
                      'of the pond? (Enter a number.)'],
        'choices': [['A', 'A. Neither gained nor lost money since his investment in 2018.'],
                    ['B', 'B. Gained money since his investment in 2018.'],
                    ['C', 'C. Lost money since his investment in 2018.']],
        'instructions': ['You will now answer seven quiz questions.',
                         'You will earn 20 yen for each correct answer.',
                         'Each question has a time limit of 60 seconds. If you do not answer within 60 '
                         'seconds, your answer will be counted as incorrect.',
                         'After answering each question, click “Next” to proceed. Once you submit an answer, '
                         'you cannot return to that question or change your answer.',
                         'Your earnings will be revealed at the end of the experiment.',
                         'If you have no questions about these rules, click “Next” to begin.'],
        'risk_title': 'Investment decision',
        'risk_intro': 'You have completed the seven quizzes. You now receive an additional 100 yen. Decide '
                      'how much to invest in a risky asset. You keep the amount you do not invest.',
        'risk_success': 'With a 50% probability, the investment succeeds and returns 2.5 times your '
                        'investment, including the invested principal.',
        'risk_failure': 'With a 50% probability, the investment fails and you lose the entire amount '
                        'invested.',
        'risk_note': 'Enter an amount from 0 to 100 yen in increments of 1 yen. There is no correct or '
                     'incorrect choice and no time limit. The computer randomly determines the outcome, '
                     'which will be revealed with your earnings on the final results page.',
        'risk_label': 'How much will you invest? (yen)',
        'risk_submit': 'Confirm investment',
        'risk_reward': 'Investment earnings',
        'risk_invested': 'Amount invested',
        'risk_outcome': 'Investment outcome',
        'risk_won': 'Success',
        'risk_lost': 'Failure'},
 'zh-hans': {'title': '测验',
             'instructions_title': '测验说明',
             'answer': '回答',
             'next': '下一步',
             'timer': '剩余时间：',
             'complete': '测验结束',
             'complete_body': '你已完成全部七道测验题。接下来请回答问卷，报酬将在提交问卷后的最终结果页面显示。',
             'to_questionnaire': '开始回答问卷',
             'questions': ['马里奥可以在5分钟内吃完一张披萨，约翰可以在20分钟内吃完一张披萨。两人一起吃完一张披萨需要多长时间？（请输入以分钟为单位的数值）',
                           '玛丽的成绩在班上既是第18高，也是第18低。班上一共有多少名学生？（请输入数值）',
                           '一名投资者以8000万日元买下一家公司，以9000万日元卖出，以9500万日元再次买入，最后以1亿1000万日元卖出。他的利润是多少百万日元？（请输入以百万日元为单位的数值）',
                           '沃伦在2018年购买了价值100万日元的股票。投资六个月后的8月11日，他购买的股票下跌了40%。幸运的是，从8月11日到11月11日，他购买的股票上涨了60%。此时，沃伦：',
                           '一根球棒和一个球总共售价5,500日元。球棒比球贵5,000日元。球多少钱？（请输入以日元为单位的数值）',
                           '如果5台机器需要5分钟生产5件产品，那么100台机器生产100件产品需要多少分钟？（请输入数值）',
                           '池塘里有一片睡莲，覆盖面积每天翻倍。如果睡莲需要48天覆盖整个池塘，那么覆盖一半池塘需要多少天？（请输入数值）'],
             'choices': [['A', 'A. 自2018年投资以来，既没有赚钱也没有亏钱。'],
                         ['B', 'B. 自2018年投资以来，赚了钱。'],
                         ['C', 'C. 自2018年投资以来，亏了钱。']],
             'instructions': ['接下来，请你回答七道测验题。',
                              '每答对一题，你将获得20日元报酬。',
                              '每题限时60秒。如果未能在60秒内回答，将视为回答错误。',
                              '回答每道题后，点击“下一步”进入下一题。一旦提交答案，就无法返回该题或修改答案。',
                              '你的报酬将在实验结束后公布。',
                              '如果对以上规则没有疑问，请点击“下一步”开始作答。'],
             'risk_title': '投资决策',
             'risk_intro': '你已完成七道测验题。现在你将额外获得100日元，请决定将其中多少投入一个风险项目。未投入的金额由你保留。',
             'risk_success': '投资有50%的概率成功，返还投入金额的2.5倍（含本金）。',
             'risk_failure': '投资有50%的概率失败，投入金额全部损失。',
             'risk_note': '请在0–100日元范围内按1日元为单位填写投资额。这项选择没有对错，也没有时间限制。电脑将随机决定投资结果，并在最终收益页统一公布结果和报酬。',
             'risk_label': '你愿意投资多少日元？',
             'risk_submit': '确认投资额',
             'risk_reward': '投资报酬',
             'risk_invested': '投资金额',
             'risk_outcome': '投资结果',
             'risk_won': '成功',
             'risk_lost': '失败'}}

TEXT = TRANSLATIONS[LANGUAGE]
